export enum EPermission {
  USER_BAN = "USER_BAN",
  SHOW_EVENTS = "SHOW_EVENTS",
  SHOW_EVENT_SUBSCRIBERS = "SHOW_EVENT_SUBSCRIBERS",
  SHOW_USERS_EVENTS = "SHOW_USER_EVENTS",
  MODIFY_EVENT_DETAILS = "MODIFY_EVENT_DETAILS",
  EVENT_SUBSCRIPTION = "EVENT_SUBSCRIPTION",
  CREATE_EVENT = "CREATE_EVENT",
  SHOW_USERS_LIST = "SHOW_USERS_LIST",
  CHANGE_ROLES = "CHANGE_ROLES",
}

export interface IModifyPermission {
  id: number;
  newName: string;
}
